config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  devise_for :users
  resources :tasks do
    collection do
      get "clear_completed"
    end
  end

  root to: "tasks#index"
end

app/models/application_record.rb
# frozen_string_literal: true

class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/task.rb
# frozen_string_literal: true

class Task < ApplicationRecord
  before_save :set_status

  validates :name, presence: true

  belongs_to :user

  scope :ordered, -> { order(id: :desc) }
  scope :search, ->(name) { where("LOWER(name) LIKE ?", "%#{name.downcase}%") if name.present? }
  scope :filter_by_status, ->(status) { where(status:) if status.present? }

  def set_status
    self.status ||= "active"
  end

  def completed?
    self.status == "completed"
  end
end

app/models/user.rb
# frozen_string_literal: true

class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable, :recoverable, :rememberable, :validatable

  has_many :tasks, dependent: :destroy

  def name
    email.split("@").first.capitalize
  end

  def total_tasks
    tasks.where(status: "active").count
  end

  def total_completed_tasks
    tasks.where(status: "completed")
  end
end

app/controllers/application_controller.rb
# frozen_string_literal: true

class ApplicationController < ActionController::Base
  before_action :authenticate_user!, unless: :devise_controller?
end

app/controllers/tasks_controller.rb
# frozen_string_literal: true

class TasksController < ApplicationController
  before_action :authenticate_user!
  before_action :set_task, only: %i[show edit update destroy]

  def index
    @tasks = current_user.tasks.search(params[:search]).filter_by_status(params[:status]).ordered
  end

  def show; end

  def new
    @task = current_user.tasks.new
  end

  def create
    @task = current_user.tasks.new(task_params)

    if @task.save
      respond_to do |format|
        format.html { redirect_to tasks_path, notice: t(:create_task) }
        format.turbo_stream { flash.now[:notice] = t(:create_task) }
      end
    else
      render :new, status: :unprocessable_entity
    end
  end

  def edit; end

  def update
    if @task.update(task_params)
      respond_to do |format|
        format.html { redirect_to tasks_path, notice: t(:update_task) }
        format.turbo_stream { flash.now[:notice] = t(:update_task) }
      end
    else
      render :edit, status: :unprocessable_entity
    end
  end

  def destroy
    @task.destroy

    respond_to do |format|
      format.html { redirect_to tasks_path, notice: t(:destroy_task) }
      format.turbo_stream { flash.now[:notice] = t(:destroy_task) }
    end
  end

  def clear_completed
    current_user.total_completed_tasks.destroy_all

    respond_to do |format|
      format.html { redirect_to tasks_path(status: "completed"), notice: t(:clear_completed_task) }
      format.turbo_stream { flash.now[:notice] = t(:clear_completed_task) }
    end
  end

  private

  def set_task
    @task = current_user.tasks.find(params[:id])
  end

  def task_params
    params.require(:task).permit(:name, :status)
  end
end

app/helpers/application_helper.rb
# frozen_string_literal: true

module ApplicationHelper
  def render_turbo_stream_flash_messages
    turbo_stream.prepend "flash", partial: "layouts/flash"
  end
end

app/views/layouts/_flash.html.erb
<% flash.each do |flash_type, message| %>
  <div
    class="flash__message"
    data-controller="removals"
    data-action="animationend->removals#remove">
    <%= message %>
  </div>
<% end %>

app/views/layouts/_navbar.html.erb
<header class="navbar">
  <% if user_signed_in? %>
    <div class="navbar__brand">
      <%= link_to current_user.name, edit_user_registration_path %>
    </div>
    <div class="navbar__action">
      <%= link_to "Sign out", destroy_user_session_path, method: :delete, data: { turbo_method: :delete }, class: "btn btn--dark" %>
    </div>
  <% else %>
    <%= link_to "Sign in",
                new_user_session_path,
                class: "btn btn--dark navbar__right" %>
  <% end %>
</header>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Todo App</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_include_tag "application", "data-turbo-track": "reload", defer: true %>
  </head>

  <body>

    <%= render "layouts/navbar" %>

    <div id="flash" class="flash">
      <%= render "layouts/flash" %>
    </div>

    <%= yield %>
  </body>
</html>

app/views/tasks/_filter.html.erb
<div class="filter">
  <div>
    <%= "#{current_user.total_tasks} tasks left" %>
  </div>

  <div>
    <ul class="filter__actions">
      <li> <%= link_to "All", tasks_path, class: ("filter__active" if params[:status].blank?) %>
      </li>

      <li> <%= link_to "Active", tasks_path(status: "active"), class: ("filter__active" if params[:status] == "active") %>
      </li>

      <li> <%= link_to "Completed", tasks_path(status: "completed"), class: ("filter__active" if params[:status] == "completed") %>
      </li>
    </ul>
  </div>

  <div class="filter__clear">
    <%= link_to "Clear Completed", clear_completed_tasks_path, method: :get %>
  </div>
</div>

app/views/tasks/_form.html.erb
<%= simple_form_for task, html: { class: "task form" } do |f| %>

<% if task.errors.any? %>
  <div class="error-message">
    <%= task.errors.full_messages.to_sentence.capitalize %>
  </div>
<% end %>

<%= f.input :name, input_html: { autofocus: true } %>
<%= link_to "Cancel", tasks_path, class: "btn btn--light" %>
<%= f.submit class: "btn btn--secondary" %>
<% end %>

app/views/tasks/_task.html.erb
<%= turbo_frame_tag task do %>
  <div class="task">
    <%= link_to task.name,
                task_path(task),
                data: { turbo_frame: "_top" } %>

    <div class="task__actions">
      <% unless task.completed? %>
        <%= button_to "Completed", task_path(task.id),
                      params: { task: { id: task.id, status: "completed", user_id: current_user.id } },
                      method: :put,
                      class: "btn btn--light" %>
      <% end %>

      <%= link_to "Edit",
                  edit_task_path(task),
                  class: "btn btn--light" %>

      <%= button_to "Delete",
                    task_path(task),
                    method: :delete,
                    class: "btn btn--light" %>
    </div>
  </div>
<% end %>

app/views/tasks/create.turbo_stream.erb
<%= turbo_stream.prepend "tasks", @task %>

<%= turbo_stream.update Task.new, "" %>

<%= render_turbo_stream_flash_messages %>

app/views/tasks/destroy.turbo_stream.erb
<%= turbo_stream.remove @task %>

<%= render_turbo_stream_flash_messages %>

app/views/tasks/edit.html.erb
<main class="container">
  <%= link_to "Back", tasks_path %>

  <div class="header">
    <h1> Edit Task </h1>
  </div>

  <%= turbo_frame_tag @task do %>
    <%= render "form", task: @task %>
  <% end %>
</main>

app/views/tasks/index.html.erb
<main class="container">
  <div class="header">
    <h1>Tasks</h1>

    <%= link_to "New task",
                new_task_path,
                class: "btn btn--primary",
                data: { turbo_frame: dom_id(Task.new) } %>
  </div>

  <div class="search">
    <%= form_with url: tasks_path, method: :get, data: { turbo_frame: "tasks", turbo_action: "advance", controller: "form", action: "input->form#submit" } do %>
      <%= text_field_tag "search", nil, autocomplete: :off, placeholder: "Search", class: "form__input" %>
    <% end %>
  </div>

  <%= turbo_frame_tag Task.new %>

  <%= turbo_frame_tag "tasks" do %>
    <%= render partial: "task", collection: @tasks %>
  <% end %>

  <%= render "filter" %>
</main>

app/views/tasks/new.html.erb
<main class="container">
  <%= link_to "Back", tasks_path %>

  <div class="header">
    <h1> New Task </h1>
  </div>

  <%= turbo_frame_tag @task do %>
    <%= render "form", task: @task %>
  <% end %>
</main>

app/views/tasks/show.html.erb
<main class="container">
  <%= link_to "Back", tasks_path %>

  <div class="header">
    <h1> <%= @task.name %> </h1>
  </div>
</main>

app/views/tasks/update.turbo_stream.erb
<%= turbo_stream.replace @task %>

<%= render_turbo_stream_flash_messages %>

app/views/users/shared/_error_messages.html.erb
<% if resource.errors.any? %>
  <div id="error_explanation">
    <h2>
      <%= I18n.t("errors.messages.not_saved",
                 count: resource.errors.count,
                 resource: resource.class.model_name.human.downcase) %>
    </h2>
    <ul>
      <% resource.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
    </ul>
  </div>
<% end %>

app/views/users/shared/_links.html.erb
<%- if controller_name != 'sessions' %>
  <%= link_to "Log in", new_session_path(resource_name) %><br>
<% end %>

<%- if devise_mapping.registerable? && controller_name != 'registrations' %>
  <%= link_to "Sign up", new_registration_path(resource_name) %><br>
<% end %>

<%- if devise_mapping.recoverable? && controller_name != 'passwords' && controller_name != 'registrations' %>
  <%= link_to "Forgot your password?", new_password_path(resource_name) %><br>
<% end %>

<%- if devise_mapping.confirmable? && controller_name != 'confirmations' %>
  <%= link_to "Didn't receive confirmation instructions?", new_confirmation_path(resource_name) %><br>
<% end %>

<%- if devise_mapping.lockable? && resource_class.unlock_strategy_enabled?(:email) && controller_name != 'unlocks' %>
  <%= link_to "Didn't receive unlock instructions?", new_unlock_path(resource_name) %><br>
<% end %>

<%- if devise_mapping.omniauthable? %>
  <%- resource_class.omniauth_providers.each do |provider| %>
    <%= link_to "Sign in with #{OmniAuth::Utils.camelize(provider)}", omniauth_authorize_path(resource_name, provider), method: :post %><br>
  <% end %>
<% end %>